### PR TITLE
Feature/auto expand container

### PR DESCRIPTION
**Pull request by dlgoodchild**
Some nice improvements here.
Firstly, I've removed the jQuery dependency which existed when collapsing/expanding nodes. Because I've localised the jQuery $ variable it means it's easier to test if it works with and without jQuery.
Renamed itterateChildren to iterateChildren.
Added new UTIL methods which use jQuery if available, otherwise fall back to native javascript.
Implemented a new configuration option for scrollbar: "resize". What this does is auto resizes the draw area according to the content. Rather than introduce an entirely new config option I reused one that was there, because if you set resize, then you wouldn't have nor need scrollbars. This has allowed me to put the Treant div into another div which then applies draggable, so I can drag the tree around within a div and move the need for scrollbars to the parent. More versatility with it's use.

Let me know what you think. Happy to rework if required.
I've tested with and without jQuery and it works exactly as before and with the new option.

### CODE REVIEW

**Comment by dlgoodchild** [comment]
This actually includes the previous 2 pull requests as each iterative change I'm making relies on the previous.

**Comment by dlgoodchild** [comment]
Just an FYI, I went over the history and the jQuery dependency has been there since the initial commit, but now it functions fully without.

**Comment by fperucic** [comment]
Nice job! sorry you had to go through this old code :)

Only one issue remains, new callback options are not useable without jQ, as you said `Util.createMerge` does not work well with functions.

**Comment by dlgoodchild** [comment]
Yeah, I'll see about getting that working for non-jQuery, the events are useful to have.

**Pull request merged**
