### PR TITLE
Feature/add additional callbacks

### PR DESCRIPTION
**Pull request by dlgoodchild**
Not sure why you can't auto-merge the changes are as minimal as possible.

This pull request allows for a new config option "callback", within that option you have (at present) 3 options: onCollapseFinished, onCreateNode and onCreateNodeCollapseSwitch. This allows for soft extension of the functionality, manipulate the tree using the onCreate* callbacks, such as child content within the collapse-switch, such as an icon or image say. The onCollapseFinished will allow for triggering events elsewhere in your page, such as repositioning or changing the display in some way.

I've update the constructor to use jQuery's extend, as the UTIL.createMerge wasn't taking into account functions; jQuery's extend function is very stable and does the same thing with additions.

### CODE REVIEW

**Comment by dlgoodchild** [comment]
There are a few minor spell corrections for the english comments in there too. All very minor.

**Comment by dlgoodchild** [comment]
If you're comfortable with the format of my changes, I've got more queued up to add. If you've any feedback with how you'd like pull requests made, please let me know and I'll do my best to conform. Let me know if there's issue with this last one and I'll update accordingly.

**Comment by dlgoodchild** [comment]
If pull request #28 gets re-merged, then I'll merge that back into this branch and update to have optional jQuery dependency.

**Comment by fperucic** [comment]
Looks good. fix the confilcts so it can be merged

**Comment by dlgoodchild** [comment]
Fixed so this pull request can be merged. Adopted the jQuery independence approach, it uses jQuery if available for extending objects.

**Comment by dlgoodchild** [comment]
Part of #31

**Pull request closed without merging**
